sitename: plan_b_russia
domain: plan-b-russia.github.io
url: https://plan-b-russia.github.io/
baseurl: /

collections:
  entries:
    output: true
    sort_by: number

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_entries"
    values:
      layout: "entry"  