baseurl: "/"
url: "https://plan-b-russia.github.io/"
sitename: plan_b_russia

collections:
  entries:
    output: true
    sort_by: number

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_entries"
    values:
      layout: "entry"  